keys:
  - &local age1sur65t9wa9s0krds32kx9h379masmkyf663wwwav2ye0v5syyv2qkaxsd8
  - &vps age1h53k3c7ljgthsngt6s7jc90j5ddftek5k5w5xrxansjz338dd9fssx88qz
  - &github age1qfyv7s27lyehskzxlkasslvfvvral68sy974pkla3sj3mak7fs4sl4tquc
creation_rules:
  - path_regex: deployment/.*\.yaml$
    key_groups:
      - age:
          - *local
          - *vps
          - *github