FROM eclipse-temurin:25-jdk
ARG HOME_DIR
ARG DATA_DIR
ARG CONTAINER_USER
ARG CONTAINER_GROUP
# Install curl for healthcheck
USER root
RUN apt-get update && apt-get install -y curl

RUN addgroup --system $CONTAINER_GROUP && adduser --system --ingroup $CONTAINER_GROUP --home $HOME_DIR $CONTAINER_USER
WORKDIR /app

# Create directories with explicit ownership
RUN mkdir -p $DATA_DIR && \
    mkdir -p $HOME_DIR/.config/jgit && \
    chown -R $CONTAINER_USER:$CONTAINER_GROUP $DATA_DIR && \
    chown -R $CONTAINER_USER:$CONTAINER_GROUP $HOME_DIR

RUN chown -R $CONTAINER_USER:$CONTAINER_GROUP /app
USER $CONTAINER_USER:$CONTAINER_GROUP
ARG JAR_FILE=build/libs/*.jar
COPY --chown=$CONTAINER_USER:$CONTAINER_GROUP  ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Duser.home=${HOME_DIR}", "-jar", "app.jar"]
