FROM openjdk:21-jdk-slim
RUN addgroup --system spring && adduser --system --ingroup spring spring
WORKDIR /app

## Add volume directory setup
VOLUME /data
RUN mkdir -p /data && \
    mkdir -p /home/spring/.config/jgit && \
    chown -R spring:spring /data && \
    chown -R spring:spring /home/spring

RUN chown -R spring:spring /app
USER spring:spring
ARG JAR_FILE=build/libs/*.jar
COPY --chown=spring:spring ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","app.jar"]