FROM openjdk:21-jdk-slim
RUN addgroup --system spring && adduser --system --ingroup spring spring
WORKDIR /app
RUN chown spring:spring /app
USER spring:spring
ARG JAR_FILE=build/libs/*.jar
COPY --chown=spring:spring ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","app.jar"]