ARG GRADLE_DIR=/home/gradle/src
# Build Stage
FROM gradle:jdk21-alpine AS build
ARG GRADLE_DIR
WORKDIR $GRADLE_DIR
COPY --chown=gradle:gradle . $GRADLE_DIR
RUN gradle build --no-daemon --exclude-task test

# Run Stage
FROM eclipse-temurin:25-jdk
ARG GRADLE_DIR
RUN addgroup --system spring && adduser --system --ingroup spring spring
WORKDIR /app
## Add volume directory setup
VOLUME /data
RUN mkdir -p /data && \
    mkdir -p /home/spring/.config/jgit && \
    chown -R spring:spring /data && \
    chown -R spring:spring /home/spring

RUN chown spring:spring /app
USER spring:spring
COPY --from=build --chown=spring:spring $GRADLE_DIR/build/libs/*.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]