[versions]
kotlin = "2.4.20"
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
nemerosa-versioning = "4.0.1"
springdoc = "3.1.1"
jgit = "7.8.0.202609011348-r"
kotlin-logging = "8.0.4"
commons-csv = "1.14.1"
kotlinx-coroutines = "1.11.0"
jsoup = "1.23.1"
hibernate = "7.4.10.Final"

[libraries]
springdoc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commons-csv" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
hibernate-processor = { module = "org.hibernate.orm:hibernate-processor", version.ref = "hibernate" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-plugin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
nemerosa-versioning = { id = "net.nemerosa.versioning", version.ref = "nemerosa-versioning" }